version: 0.2

phases:
  install:
    commands:
      - cd serverless-etl-pipeline
      - echo Installing dependencies...
      - pip install -r requirements.txt

  build:
    commands:
      - echo Checking Python syntax...
      - python -m py_compile lambda/lambda_function.py
      - echo Build successful!

artifacts:
  files:
    - '**/*'
